#!/bin/sh

# convert all flac files in the current dir

for i in *.flac; do
    BASE=`basename "$i" .flac`
    metaflac --export-tags-to=current-track.tags.txt "$i"
    flac -c -d "$i" | lame -q 0 -m s -cbr -b 320 - "$BASE.mp3"
    tagmp3fromfile --tags-file=current-track.tags.txt "$BASE.mp3"
    rm -f current-track.tags.txt
done
