#!/usr/bin/env python

from optparse import OptionParser
from sys import exit
import codecs
import eyed3

parser = OptionParser(usage='%prog --tags-file=TAGS_FILE MP3_FILE')
parser.add_option('-f', '--tags-file', dest='tags_file',
    help='File that contains tags values in the form of lines TAGNAME=TAGVALUE')

(options, args) = parser.parse_args()

if options.tags_file is None:
    print('Option --tags-file is required')
    exit(1)

if len(args) != 1:
    print('One file must be provided as an argument.')
    exit(1)

mp3_filename = args[0].decode('utf8')

try:
    _ = codecs.open(options.tags_file, encoding='utf8')
    taglines = [x.strip() for x in _]
except IOError:
    print('Cannot open file "{}"'.format(options.tags_file) )
    exit(1)

tags = {}
for _ in taglines:
    p = _.find('=')
    if p == -1:
        continue
    tag, value = _[:p], _[p+1:]
    tags[tag] = value

'''
Known tags: comment, album, title, artist, track, year, tracknumber, genre
'''
tags_def_map = {
    'artist': 'setArtist',
    'comment': 'addComment',
    'album': 'setAlbum',
    'title': 'setTitle',
    'year': 'setDate'
    #'tracknumber': 'setTrackNum',
    #'genre': ''
}

audio = eyed3.load(mp3_filename)
audio.tag = eyed3.id3.tag.Tag()
audio.tag.title = tags[u'title']
audio.tag.album = tags[u'album']
audio.tag.artist = tags[u'artist']
audio.tag.track_num = int(tags[u'tracknumber'])

audio.tag.comments.set(tags[u'COMMENT'])

fr = eyed3.id3.frames.TextFrame(b'TCON')
fr.text = tags[u'GENRE']
audio.tag.frame_set[b'TCON'] = fr

fr = eyed3.id3.frames.TextFrame(b'TDRC')
fr.text = tags[u'DATE']
audio.tag.frame_set[b'TDRC'] = fr

audio.tag.save()
